[build-system]
requires = ['setuptools>=68']
build-backend = 'setuptools.build_meta'

[project]
name = 'xxm'
version = '0.1.0'
description = 'A lightweight JAX implementation of SLDS inference routines, inspired by ssm.'
readme = 'README.md'
license = 'MIT'
requires-python = '>=3.11'
dependencies = [
    'jax',
    'jax-tqdm',
    'numpy',
]

[dependency-groups]
dev = [
    'pre-commit',
    'pyright',
    'pytest',
    'ruff',
]

[tool.setuptools.packages.find]
where = ['src']

[tool.setuptools.package-data]
nocte = ['py.typed']

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint]
extend-select = ['I']

[tool.pyright]
exclude = [
    '**/node_modules',
    '**/__pycache__',
    '**/__editable__.*',
    '**/.*',
]